//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дія в Україні.
        /// </summary>
        internal static string ActionInUkraine {
            get {
                return ResourceManager.GetString("ActionInUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати Ідею.
        /// </summary>
        internal static string AddIdea {
            get {
                return ResourceManager.GetString("AddIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блоги.
        /// </summary>
        internal static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть категорію.
        /// </summary>
        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть зображення для лого.
        /// </summary>
        internal static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперішній пароль.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кінець.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цілі.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TУТ!.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідеї.
        /// </summary>
        internal static string Ideas {
            get {
                return ResourceManager.GetString("Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найкращі ідеї місяця.
        /// </summary>
        internal static string IdeasOfTheMonth {
            get {
                return ResourceManager.GetString("IdeasOfTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву.
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження аплцікації.....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Го реєструватися чи логуватися.
        /// </summary>
        internal static string LogInOrSignUp {
            get {
                return ResourceManager.GetString("LogInOrSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОЄ.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погоняло.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткові опції.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початок.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП-Блоги.
        /// </summary>
        internal static string TopBlogs {
            get {
                return ResourceManager.GetString("TopBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП-Коментарі.
        /// </summary>
        internal static string TopComments {
            get {
                return ResourceManager.GetString("TopComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП-Новини.
        /// </summary>
        internal static string TopNews {
            get {
                return ResourceManager.GetString("TopNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої коментарі.
        /// </summary>
        internal static string YourComments {
            get {
                return ResourceManager.GetString("YourComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої Ідеї.
        /// </summary>
        internal static string YourIdeas {
            get {
                return ResourceManager.GetString("YourIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої новини.
        /// </summary>
        internal static string YourNews {
            get {
                return ResourceManager.GetString("YourNews", resourceCulture);
            }
        }
    }
}
